# Generated by Django 3.0 on 2020-04-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='RestaurantReview',
        ),
    ]
