# Generated by Django 3.0 on 2020-04-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0002_auto_20200424_0440"),
    ]

    operations = [
        migrations.DeleteModel(name="RestaurantReview",),
    ]
