# Generated by Django 3.0 on 2020-05-27 10:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20200527_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='meetupevent',
            name='price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], max_length=4), size=None),
        ),
    ]
