# Generated by Django 3.0 on 2020-05-27 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20200527_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupevent',
            name='price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')]), size=None),
        ),
    ]
