# Generated by Django 3.0 on 2020-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_auto_20200527_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
