# Generated by Django 3.0 on 2020-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0006_auto_20200424_0738"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
