# Generated by Django 3.0 on 2020-06-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_restauranthours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='meetup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetup.Meetup'),
        ),
    ]
