# Generated by Django 3.0 on 2019-12-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_auto_20191231_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='creator',
        ),
    ]
