# Generated by Django 3.0 on 2019-12-31 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_remove_friendship_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='friend_creators', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
