# Generated by Django 3.0 on 2020-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_auto_20200606_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
