# Generated by Django 3.0 on 2020-04-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0008_auto_20200424_1842"),
    ]

    operations = [
        migrations.DeleteModel(name="RestaurantVote",),
    ]
