# Generated by Django 3.0 on 2020-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_auto_20200101_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='chatroomname', max_length=200),
            preserve_default=False,
        ),
    ]
