# Generated by Django 3.0 on 2020-04-25 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0010_auto_20200424_2313"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
