# Generated by Django 3.0 on 2020-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0011_auto_20200128_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='chosen',
            field=models.TextField(blank=True),
        ),
    ]
