# Generated by Django 3.0 on 2020-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0011_chatroom_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='is_notif',
            field=models.BooleanField(default=False),
        ),
    ]
