# Generated by Django 3.0 on 2020-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0012_chatroommessage_is_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
