# Generated by Django 3.0 on 2020-02-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0012_auto_20200129_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='name',
            field=models.CharField(default='Meetup', max_length=255),
        ),
    ]
