# Generated by Django 3.0 on 2020-02-03 02:07

from django.db import migrations, models
import meetup.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0014_meetupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupinvite',
            name='uri',
            field=models.URLField(default=meetup.models.generate_unique_uri),
        ),
    ]
