# Generated by Django 3.0 on 2020-02-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0016_auto_20200204_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendinvites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendinvites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetupinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_meetupinvites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetupinvite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_meetupinvites', to=settings.AUTH_USER_MODEL),
        ),
    ]
