# Generated by Django 3.0 on 2020-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0017_auto_20200525_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.SlugField(),
        ),
    ]
