# Generated by Django 3.0 on 2020-02-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0018_auto_20200208_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
