# Generated by Django 3.0 on 2020-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0019_meetup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevent',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
