# Generated by Django 3.0 on 2020-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0021_auto_20200209_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='api_label',
            field=models.CharField(default='api', max_length=255),
            preserve_default=False,
        ),
    ]
