# Generated by Django 3.0 on 2020-02-12 00:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0022_category_api_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevent',
            name='entries',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Food': 1}),
            preserve_default=False,
        ),
    ]
