# Generated by Django 3.0 on 2020-02-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0023_meetupevent_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupeventoptionvote',
            name='status',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike'), (3, 'Ban')]),
        ),
    ]
