# Generated by Django 3.0 on 2020-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0024_auto_20200217_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupeventoption',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
