# Generated by Django 3.0 on 2020-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0025_meetupeventoption_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupevent',
            name='chosen',
            field=models.IntegerField(default=0),
        ),
    ]
