# Generated by Django 3.0 on 2020-02-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0026_auto_20200220_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupevent',
            name='chosen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
