# Generated by Django 3.0 on 2020-02-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0027_auto_20200220_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
