# Generated by Django 3.0 on 2020-02-23 18:54

from django.db import migrations, models
import meetup.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0028_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/blank_profile_pic.png', null=True, upload_to=meetup.models.wrapper),
        ),
    ]
