# Generated by Django 3.0 on 2020-02-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0030_auto_20200223_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'Meetup'), (2, 'Friend')], default=1),
            preserve_default=False,
        ),
    ]
