# Generated by Django 3.0 on 2020-02-23 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0031_chatroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='friendship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetup.Friendship'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='meetup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetup.Meetup'),
        ),
    ]
