# Generated by Django 3.0 on 2020-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0034_remove_chatroommessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevent',
            name='distance',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetupevent',
            name='price',
            field=models.CharField(default='1, 2, 3', max_length=10),
            preserve_default=False,
        ),
    ]
