# Generated by Django 3.0 on 2020-02-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0035_auto_20200227_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevent',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='meetup.MeetupMember'),
            preserve_default=False,
        ),
    ]
