# Generated by Django 3.0 on 2020-03-02 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0036_meetupevent_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='datetime',
        ),
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 1)),
            preserve_default=False,
        ),
    ]
