# Generated by Django 3.0 on 2020-03-02 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0037_auto_20200301_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupevent',
            name='location',
        ),
        migrations.AlterField(
            model_name='meetupevent',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 20, 36, 2, 900026)),
            preserve_default=False,
        ),
    ]
