# Generated by Django 3.0 on 2020-03-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0039_auto_20200302_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupeventoption',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
