# Generated by Django 3.0 on 2020-03-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0040_meetupeventoption_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupeventoptionvote',
            name='user',
        ),
        migrations.AddField(
            model_name='meetupeventoptionvote',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member_votes', to='meetup.MeetupMember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetupmember',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
