# Generated by Django 3.0 on 2020-03-08 20:47

from django.db import migrations, models
import meetup.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0041_auto_20200305_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=meetup.helpers.PathAndRename('avatar')),
        ),
    ]
