# Generated by Django 3.0 on 2020-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0042_auto_20200308_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Lee', max_length=255),
            preserve_default=False,
        ),
    ]
