# Generated by Django 3.0 on 2020-03-20 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0043_auto_20200313_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='label',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='profile',
        ),
        migrations.AddField(
            model_name='meetup',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=-122.258423, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=37.871853, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetupcategory',
            name='meetup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetup_categories', to='meetup.Meetup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetup.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetupcategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='meetup.MeetupEvent'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
