# Generated by Django 3.0 on 2020-03-20 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0044_auto_20200320_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
