# Generated by Django 3.0 on 2020-03-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0045_preference_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
