# Generated by Django 3.0 on 2020-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0046_preference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='ranking',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
