# Generated by Django 3.0 on 2020-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0048_auto_20200322_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
