# Generated by Django 3.0 on 2020-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0054_auto_20200327_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
