# Generated by Django 3.0 on 2020-03-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0055_auto_20200327_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
