# Generated by Django 3.0 on 2020-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0058_auto_20200327_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
