# Generated by Django 3.0 on 2020-03-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0060_usersettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevent',
            name='random',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='radius',
            field=models.IntegerField(default=10),
        ),
    ]
