# Generated by Django 3.0 on 2020-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0062_auto_20200420_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('url', models.TextField()),
                ('rating', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('categories', models.TextField()),
            ],
        ),
    ]
