# Generated by Django 3.0 on 2020-04-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0064_restaurantpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_restaurants', to='meetup.Category')),
                ('restauraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_categories', to='meetup.Restaurant')),
            ],
        ),
    ]
