# Generated by Django 3.0 on 2020-04-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0065_restaurantcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupeventoption',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetup_options', to='meetup.Restaurant'),
        ),
        migrations.AlterField(
            model_name='meetupeventoption',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
