# Generated by Django 3.0 on 2020-04-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0067_auto_20200421_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(),
        ),
    ]
