# Generated by Django 3.0 on 2020-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0069_auto_20200423_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
