# Generated by Django 3.0 on 2020-04-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0070_auto_20200423_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(default='Address 1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='City', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='City', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zipcode',
            field=models.CharField(default='91214', max_length=255),
            preserve_default=False,
        ),
    ]
