# Generated by Django 3.0 on 2020-04-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0071_auto_20200423_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='CA', max_length=255),
            preserve_default=False,
        ),
    ]
