# Generated by Django 3.0 on 2020-04-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0073_auto_20200423_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='option_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
