# Generated by Django 3.0 on 2020-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0074_auto_20200423_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
