# Generated by Django 3.0 on 2020-04-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0076_auto_20200423_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
