# Generated by Django 3.0 on 2020-04-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0078_auto_20200423_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='yelp_image',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='url',
            new_name='yelp_url',
        ),
    ]
