# Generated by Django 3.0 on 2020-04-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0079_auto_20200423_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
